### ISSUE TITLE
NullInjectorError: No provider for NgxPrinterService!

### ISSUE THREAD

**Issue by danny-4884** [plaetzchen79/ngx-printer-demo#17]
For angular 8

**Comment by LouiMinister** [comment]
I got same problem and I figured out how to make it works.
There is only mention like this in readme.md.
" Add to main app.module imports "

It means you have to write code like below in app.module.ts
```
import { NgxPrinterModule, NgxPrinterService } from 'ngx-printer';

imports: [
  NgxPrinterModule.forRoot({printOpenWindow: false}),
],
providers: [
  NgxPrinterService
],
```

I hope it will help u

**Comment by JuanDa237** [comment]
@LouiMinister, Thanks, that works for me.
If i want use the directives i've to import them too?

**Comment by plaetzchen79** [comment]
solution provided
