### ISSUE TITLE
Compatible with Ivy (angular 10).

### ISSUE THREAD

**Issue by MubeenTahirCheema** [plaetzchen79/ngx-printer-demo#18]
getting error just after importing in app.module

"This likely means that the library (ngx-printer/lib/ngx-printer.module) which declares NgxPrinterModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy."

**Comment by plaetzchen79** [comment]
Accoring to https://stackoverflow.com/questions/63627932/angular-10-libraries-and-ivy-ngcc-compatibility

i should check 
"scripts": {
    "postinstall": "ngcc"
  }

or
https://github.com/angular/angular/issues/36060

**Comment by plaetzchen79** [comment]
hmm forcing ivy says:
******************************************************************************
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility

**Comment by plaetzchen79** [comment]
Starting wit 0.9 i will upgrade to Angular 11 and then set **Ivy** as default.
