### ISSUE TITLE
Print directly without preview via printservice is not defined in the documentation

### ISSUE THREAD

**Issue by tech-srinath** [plaetzchen79/ngx-printer-demo#19]
I'm using ngx-printer repo for printing an angular component via print service but i'm not able to find the documentation for sending a print job directly to the printer.

**Comment by plaetzchen79** [comment]
This is currently not supported.
I dont really know if its possible without using a bigger cannon.  One library i know which can do this -over different os- is electron. But as far as i know they even use c++ to direct call the os (default) printer.
This library is small and i dont want to include other dependencies.
Please correct me if i am wrong.

**Comment by tech-srinath** [comment]
So I went around searching for alternatives but I could only find one called `pdf-to-printer` but this mostly used with node js and not as a front-end dependency.

**Comment by tech-srinath** [comment]
I totally agree. There has to be an OS support to access the printer connected to the system for direct printing. 
However, it is not difficult to add such functionality for Electron users but if the project uses a browser, then what we need is to use an **Asynchronous pluggable protocol handler**.
This requires the user to manually install the handler in the registry and whitelist the protocol in the browser.
This is too much hard work but I wasn't able to find a better solution for direct printing via the browser.
I used Python for creating the custom executable for managing the print jobs in my project.
But I must say that your work is amazing.
