### ISSUE TITLE
Print selective items inside a div

### ISSUE THREAD

**Issue by bhuvana-abhisheg** [plaetzchen79/ngx-printer-demo#21]
Hi Plaetzchen79, 
Is there any option to print selective elements inside a div.

Ex:
<div id="main">
<span>This shouldnt be printed </span>
<span> This should be printed <span>
<div>
In my project i have an usecase where i have to skip printing certain elements in my html. Can u pls let me know whether there is an option to do this. In ng-print library we have a directive called noPrint, which will allow us to hide certain elements in Print.

**Comment by plaetzchen79** [comment]
hi @bhuvana-abhisheg 
Not directly. I shold consider to add it.
What you can try:
You can store all the items (divs) you _want_ to print with the directive `ngxPrintItem `. 
But this will not work if you dont want to print divs _inside_ the divs to be printed.

**Comment by bhuvana-abhisheg** [comment]
Hi @plaetzchen,
Thanks for the reply.
Will definitely try.

Regards,
Bhuvana.

**Comment by plaetzchen79** [comment]
Added with 0.9.1
