### ISSUE TITLE
The `printOpenWindow` can not load the global style.css

### ISSUE THREAD

**Issue by ngoquoc** [plaetzchen79/ngx-printer-demo#22]
My Angular app is using the [default PathLocationStragey](https://angular.io/api/common/PathLocationStrategy)

And in one of my page, says `/masterPage/detail/:id`, I have this printing functionality set up:

```
this._printerService.timeToWaitRender = 1500;
this._printerService.printOpenWindow = true;

this._printerService.printDiv('myDivId');
```

Issue: when it opens the print window, it has the following stylesheet tag in the generated HTML document:
`<link rel="stylesheet" href="styles.76979927b9a7bc88a048.css">`

However, the browser tries to look at `{hostname}/masterPage/detail/styles.76979927b9a7bc88a048.css` instead of `{hostname}/styles.76979927b9a7bc88a048.css`.

I actually checked the implementation of `copyCss` functionality and everything looks great:
https://github.com/plaetzchen79/ngx-printer-demo/blob/99b0fad2a387001f1d757728fa4e640a8dd7def2/projects/ngx-printer/src/lib/ngx-printer.service.ts#L254-L267

However, it only copies the `link` and `style` tags, and ignores everything else. What I think it should do is to copy also the `base` tag which tells the browser what would be the relative path of the CSS resources to load from.

**Comment by ngoquoc** [comment]
@plaetzchen79 could you please take a look at my PR and consider merging it to the codebase? I'm looking forward to having this PR merged so I can use the official NPM package (for now I have to use a local package - which is basically the built output of my forked repo).

**Comment by plaetzchen79** [comment]
Thank you for the pull request! :-)
I am happy to get some help.
I am now on holiday and i will merge and deploy a new version soon.

**Comment by plaetzchen79** [comment]
Done with 0.9.1
