### ISSUE TITLE
unable to print from same window/tab

### ISSUE THREAD

**Issue by Prabin1111** [plaetzchen79/ngx-printer-demo#25]
i want to print page without opening new tab so i had set root config as 

in app.module
`    NgxPrinterModule.forRoot({printOpenWindow: false});
`

featureModule have sales feature so i have to print bill so code as 
in sales component i have call print component from shared module
`
<button (click)="printHTMLElementToCurrent()">print</button>
<app-print #printContainer>
</app-print>`

sales.component.ts

` 
@ViewChild('printContainer', {read: ElementRef}) PrintComponent: ElementRef | undefined;

  constructor(private printerService: NgxPrinterService) { }
  ngOnInit(): void {
  }
  printHTMLElementToCurrent(): void {
    this.PrintComponent && 
    this.printerService.printHTMLElement(this.PrintComponent.nativeElement);
  }
`
i need help to fixed this issue

angular dependency 

"
 "dependencies": {
    "@angular/animations": "~10.0.0",
    "@angular/cdk": "^11.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@prajna10/sd_design": "0.0.29",
    "ngx-printer": "^0.9.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  }

**Comment by donbwhite** [comment]
Encountering this issue as well. Hope it can be patched.

@plaetzchen79 in case it helps I did downgrade to 0.9.0 to check just in case it was related to issue 22 since that seemed related to the printOpenWindow but had the same behavior. Wanted to report and rule that out for you.

**Comment by plaetzchen79** [comment]
Sorry for beeing late.
Do you have any console error output?
What happend? Does the print dialog appear - or nothing happens?

**Comment by Prabin1111** [comment]
NO error message in console
screen recorded link 
[https://drive.google.com/file/d/1XLSnXNhtyJIlzsUyHR69-_U2Ey8gmi0n/view](url)

**Comment by plaetzchen79** [comment]
Thank you!!
Call me blind or stupid-but i cant figure out..
1. The print window opens in the current window
2. Content is shown
3.. it closes correctly and returns to the window

But in 2):
The content is **not** correct- the content of a shared component is missing?

**Comment by plaetzchen79** [comment]
or is it the fact that a new window opens?

in this case can you try this:

```
  printHTMLElementToCurrent() {
    this.printerService.printOpenWindow = false;
    this.printerService.printHTMLElement(this.PrintComponent.nativeElement);
    this.printerService.printOpenWindow = true;
  }
```

**Comment by donbwhite** [comment]
I would assume that if printOpenWindow was set to false then the new tab/window would not open and it would just open up the browsers print.

**Comment by plaetzchen79** [comment]
ahh ok forRoot parameter false boolean check..i will fix this

**Comment by plaetzchen79** [comment]
please try Version 0.9.2

**Comment by Prabin1111** [comment]
load print page by `Ctrl + P` 
What we are expecting
[https://drive.google.com/file/d/1Iyo9M0L-pkXiTjiFGaDarHoAhIOHs6_i/view`](url)

load print page by library service `this.printerService.printHTMLElement(this.PrintComponent.nativeElement);`
what we get
[https://drive.google.com/file/d/1Iyo9M0L-pkXiTjiFGaDarHoAhIOHs6_i/view](url)

also thank you for response

I will try 0.9.2 and info soon

**Comment by Prabin1111** [comment]
@plaetzchen79  

The print window/box open in the current window

but the content of page is now blank 

[https://drive.google.com/file/d/1rAJf2AmPJVUDb2tjw4nk0Cib1X6-DqK4/view ](url)

Am i doing it wrong way or need to add more config

in app.module
`NgxPrinterModule.forRoot({printOpenWindow: false});`

HTML
`
<button (click)="printHTMLElementToCurrent()">print</button> 
<app-print  #printContainer ngxPrintItem  directPrint="true">
    <app-print-header>
        <app-print-header-mock-up></app-print-header-mock-up>
    </app-print-header>
    <app-print-body>
        <app-print-body-mock-up> </app-print-body-mock-up>
    </app-print-body>
    <app-print-footer>
    </app-print-footer>
  </app-print>
`

component
`@ViewChild('printContainer', {read: ElementRef}) PrintComponent: ElementRef | undefined;

constructor(private printerService: NgxPrinterService) { }
ngOnInit(): void {
}
printHTMLElementToCurrent(): void {
this.PrintComponent &&
this.printerService.printHTMLElement(this.PrintComponent.nativeElement);
}`
