### ISSUE TITLE
Option to add a custom/prefilled filename when saving as pdf

### ISSUE THREAD

**Issue by KenKeymolen** [plaetzchen79/ngx-printer-demo#35]
Hello! First of all thanks for this awesome plugin, it works really well. 
I'm looking for a way to add a custom filename so the user doesn't have to enter it when saving the html to a pdf. Is this already possible?

Thanks in advance

**Comment by plaetzchen79** [comment]
Hello!
I am not sure what you mean. I havent done any exlicit funtion that saves an html as a pdf within this library.
Perhaps a built-in browser function?

**Comment by KenKeymolen** [comment]
Thanks for your reply!

So when a user tries to print a document, the print preview window will open. There he can select for example "Microsoft print to PDF". When he clicks the "print" button, it'll open a file explorer window in which he has the enter a filename himself. Is it possible to prefill this already so the user doesn't have to enter a filename?  Something like: this.printer.printDiv('print-wrapper', 'myCustomFilename'); 

Thanks in advance
