### ISSUE TITLE
useExistingCss does not work

### ISSUE THREAD

**Issue by spyasar** [plaetzchen79/ngx-printer-demo#45]
I tried useExistingCss and styleSheetFile both are not working. only printStyle is working fine. Here is my code

<div id="printContent">
....
</div>
<button printSectionId="printContent" [useExistingCss]="true" [printStyle]="{printCss}" styleSheetFile="assets/css/print.css" ngxPrint>print</button>

**Comment by plaetzchen79** [comment]
Are you sure you are in the right project? 
There is no `styleSheetFile ` property in the settings,
