### ISSUE TITLE
White Space on top 

### ISSUE THREAD

**Issue by punt0com** [plaetzchen79/ngx-printer-demo#58]
This library works wonder, but whenever I print my angular component, in all the pages once the PDF is finished there is always a really big white space that takes around 15% of the view, how can that whites space be eliminated ?

**Comment by plaetzchen79** [comment]
hmm you are talking about pdf..this library cant influce the os-side conversion to pdf (i think selecting a pdf output as a printer).

Perhaps -if you print to current window- the `renderClass` property may help..

<img width="411" alt="image" src="https://user-images.githubusercontent.com/20906698/193448573-bcd93a60-b2a6-49f1-9967-3d218207dfab.png">
