### ISSUE TITLE
Image is not loading in print preview

### ISSUE THREAD

**Issue by glnarayana** [plaetzchen79/ngx-printer-demo#9]
Hi,
I am having difficulty in printing image.Image is loading alternative times if i use property printOpenWindow: true else blank preview is getting displayed.
Image i tried is from this https://ng-bootstrap.github.io/#/components/carousel/examples

`const printContent = document.getElementsById("image-tag");
 this.printerService.printImg(printContent.src);`

**Comment by plaetzchen79** [comment]
Hi, 
hmm this one works for me:

```
  printImage2() {
    const printContent = <HTMLImageElement> document.getElementById('imId2');
    this.printerService.printOpenWindow = true;
    this.printerService.printImg(printContent.src);
  }
```

In your case you can also use 
`  this.printerService.printHTMLElement(printContent.nativeElement);`

Or you can use the directive  ngxPrintItemMarker 

```
<div ngxPrintItemMarker directPrint="true">
  <img src="lll" />
</div>
```

Hope this helps.
Greetings.
